APT::FTPArchive::Release {
  Origin "Hemantha-Test";
  Label "Hemantha-Test";
  Suite "stable";
  Codename "stable";
  Architectures "arm64 all";
  Components "main";
  Description "Hemantha Test Repository updated with new key";
};
